"use client";
import { FormEvent, useEffect, useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
export default function Profiles(){
 const [profiles,setProfiles]=useState<any[]>([]); const [message,setMessage]=useState("");
 const token=()=>localStorage.getItem("kall_token");
 async function load(){const r=await fetch(`${API}/api/me/professional-profiles`,{headers:{Authorization:`Bearer ${token()}`}});if(r.ok)setProfiles(await r.json());}
 useEffect(()=>{load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const lines=(n:string)=>String(f.get(n)||"").split("
").map(x=>x.trim()).filter(Boolean);const csv=(n:string)=>String(f.get(n)||"").split(",").map(x=>x.trim()).filter(Boolean);
 const payload={name:f.get("name"),target_titles:lines("titles"),industries:csv("industries"),functional_areas:csv("functions"),include_keywords:csv("include"),exclude_keywords:csv("exclude"),countries:csv("countries"),states_regions:csv("states"),work_types:csv("work_types"),minimum_base:Number(f.get("min")||0)||null,target_base:Number(f.get("target")||0)||null,stretch_base:Number(f.get("stretch")||0)||null};
 const r=await fetch(`${API}/api/me/professional-profiles`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`},body:JSON.stringify(payload)});setMessage(r.ok?"Profile created.":"Could not create profile.");if(r.ok){e.currentTarget.reset();load();}}
 return <main className="shell"><header className="topbar"><div className="brand">Kall Profiles</div><nav><a href="/jobs">Jobs</a><a href="/resumes">Resume Studio</a></nav></header><div className="grid"><article className="card"><h1>Create a professional profile</h1><form className="form" onSubmit={submit}><input className="input" name="name" placeholder="Profile name" required/><textarea className="input" name="titles" rows={5} placeholder="One target title per line"/><input className="input" name="industries" placeholder="Industries, comma separated"/><input className="input" name="functions" placeholder="Functional areas"/><input className="input" name="include" placeholder="Include keywords"/><input className="input" name="exclude" placeholder="Exclude keywords"/><div className="two"><input className="input" name="countries" placeholder="Countries"/><input className="input" name="states" placeholder="States or regions"/></div><input className="input" name="work_types" defaultValue="remote,hybrid"/><div className="two"><input className="input" name="min" type="number" placeholder="Minimum base"/><input className="input" name="target" type="number" placeholder="Target base"/></div><input className="input" name="stretch" type="number" placeholder="Stretch base"/><button className="button">Create profile</button></form><p>{message}</p></article><article className="card"><h2>Your profiles</h2>{profiles.map(p=><div key={p.id} style={{borderBottom:"1px solid #eee",padding:"12px 0"}}><b>{p.name}</b><p>{p.target_titles.join(" · ")}</p><a className="button secondary" href={`/jobs?profile=${p.id}`}>View jobs</a></div>)}</article></div></main>;
}
